### ISSUE TITLE
Erro de responsividade

### ISSUE THREAD

**Issue by CauaStupp** [betafontes/anime-newslatter#1]
# Erro no h2 do aside
### Você colocou um line-height no h2 e esqueceu de mexer nele quando a tela diminuía, então quando a tela for menor coloque ele como 100% ou com medidas relativas como o rem. Notei também que você não deu um reset no seu css, é sempre bom dar um reset nele quando você for fazer suas interfaces.

NeverStopLearning 😄

**Comment by betafontes** [comment]
irei tentar resolver esse problema, muito obrigada por ter notado!
